---
Code:
  youtube:
    title: Видеоролик YouTube
    text: Вставляет проигрыватель Ютуба
    html: '<iframe width="[2:640]" height="[3:480]" src="http://www.youtube.com/embed/[1]" frameborder="0" allowfullscreen></iframe>'
    placeholder: Код_видео
    is_single: 1
  alert:
    title: Внимание
    text: Блок с подложкой и текстом
    html: '<div class="alert alert-info"><h4>[1]</h4>[content]</div>'
    placeholder:
    is_single: 0
  sub:
    title: Нижний индекс
    text:
    html: '<sub>[content]</sub>'
    placeholder:
    is_single: 0
  sup:
    title: Верхний индекс
    text:
    html: '<sup>[content]</sup>'
    placeholder:
    is_single: 0
  right:
    title: Выравнивание по правому краю
    text:
    html: '<div class="right">[content]</div>'
    placeholder:
    is_single: 0
    